# Generated by Django 4.2.13 on 2024-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Kategoria')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategoriat',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nimi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kuvaus')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Hinta')),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Alennettu hinta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Kuva')),
                ('quantity', models.IntegerField(default=0, verbose_name='Määrä')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Tuote',
                'verbose_name_plural': 'Tuotteet',
            },
        ),
    ]
