# Generated by Django 4.2.13 on 2024-06-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Tuote', 'verbose_name_plural': 'Tuotteet'},
        ),
    ]
