# Generated by Django 4.2.13 on 2024-07-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'tuote', 'verbose_name_plural': 'tuotteet'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
